name: Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install Dependencies
        # run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        # run: composer update --ignore-platform-reqs

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Config Clearing
        run: php artisan config:clear

      - name: Cache Clearing
        run: php artisan cache:clear

      - name: Generate App Key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 92.205.6.6
          username: task@taskmgr.roomzhub.com
          password: OQ!cF57Qzg1e249011
          server-dir: /
